### ISSUE TITLE
Add a class to have fixed layouts

### ISSUE THREAD

**Issue by jeradrutnam** [wso2-dev-ux/theme-wso2#53]
Suggestion:

```css
body.layout-fixed {
    height: 100%;
}
```
